/** Assets from Desktop/New assets + Figma exports for frame 5224:17386 */
export const FIGMA = {
  sidebarHero: "/figma/sidebar-hero.svg",
  logos: {
    deloitte: "/figma/logo-deloitte.svg",
    eu: "/figma/logo-eu.svg",
    qualitas: "/figma/logo-qualitas.svg",
    novartis: "/figma/logo-novartis.svg",
    procore: "/figma/logo-procore-mark.svg",
    investview: "/figma/logo-investview.svg",
    cma: "/figma/logo-cma.svg",
    petronas: "/figma/logo-petronas.svg",
    malaysia: "/figma/logo-malaysia.svg",
    vodafone: "/figma/logo-vodafone.svg",
    busybees: "/figma/logo-busybees.svg",
    images1: "/figma/logo-images1.svg",
  },
  procoreWordmark: "/figma/procore-wordmark.svg",
  novartisWordmark: "/assets/novartis-wordmark-figma5248.svg",
  mockupSafety: "/figma/mockup-safety.svg",
  mockupMeridian: "/figma/mockup-meridian.svg",
  mockupIcancare: "/figma/mockup-icancare.svg",
  cardRings: "/figma/card-rings.svg",
  cardMalaysia: "/figma/card-malaysia.png",
  cardComingSoon: "/figma/card-coming-soon.png",
  dots: [
    "/figma/dot-1.svg",
    "/figma/dot-2.svg",
    "/figma/dot-3.svg",
    "/figma/dot-4.svg",
  ] as const,
  expProcore: "/figma/exp-procore.svg",
  expCaspian: "/figma/exp-caspian.svg",
  expSpiritude: "/figma/exp-spiritude.svg",
  iconLinkedIn: "/figma/icon-linkedin.svg",
  iconEmail: "/figma/icon-email.svg",
} as const;
