export const HERO_MARQUEE_ITEMS = [
  "Figma",
  "Claude",
  "Cursor",
  "NotebookLM",
  "Framer",
  "No-code Builders",
  "Jira",
  "Trello",
  "Notion",
  "FigJam",
  "Atlassian",
  "Wireframing",
  "Prototyping",
  "Interaction Design",
  "Information Architecture",
  "Design Systems",
  "Accessibility",
  "UX Writing",
  "Prompt Engineering",
  "AI Integration",
  "WCAG",
  "User Research",
  "Usability Testing",
  "Data-Driven Design",
  "Agile / Scrum",
  "Design Thinking",
] as const;
